config/routes.rb
Rails.application.routes.draw do
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :posts, only: [:index, :new, :create]
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true, length: {maximum: 150}
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_user_token
  before_save {self.email = email.downcase}
  
  validates :name, presence: true, length: {maximum:50}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:50}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}
  has_many :posts
  
  private
    def create_user_token
      remember_token = SecureRandom.urlsafe_base64
      self.remember_token = Digest::SHA1.hexdigest(remember_token)
      #remember_token = SecureRandom.urlsafe_base64
      #encrypted_token = Digest::SHA1.hexdigest(remember_token)
      #self.remember_token = encrypted_token 
    end
  
    def self.digest(string)
          cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)

    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  def sign_in(user)
    remember_token = SecureRandom.urlsafe_base64
    cookies.permanent[:remember_token] = remember_token
    self.current_user = user
    #byebug
  end
  
  def current_user
    @current_user ||= User.find_by(remember_token: Digest::SHA1.hexdigest(cookies[:remember_token])) 
    #byebug
    return @current_user
  end
  
  def current_user=(user)
    #byebug
    rt = Digest::SHA1.hexdigest(cookies[:remember_token])
    puts "Want to update the rt with #{rt}"#.colorize(:red)
    user.update_attribute(:remember_token, rt)
  end
  
  def sign_out
    #byebug
    current_user.remember_token = nil unless current_user.nil?
    cookies[:remember_token] = nil
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def display_name(user)
    signed_in? ? user.email : "Anonymous"
  end
  
  helper_method :display_name #so that view can see it
  helper_method :signed_in?
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create]
  

  
  def new
    @post = Post.new
  end
  
  def create
    # needs error handling! 
    @post = current_user.posts.create(post_params)
    if @post.valid?
      redirect_to :posts  
    else
      flash.now[:error] = "Error in post"
      render 'posts/new'      
    end
    
  end
  
  def index
    #@posts = Post.all --> Notice a lot of noise querying for each user who wrote each post after the fact
    @posts = Post.includes(:user).all # use this to reduce the N+1 query problem
  end
  
  
  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
    
    def signed_in_user
      redirect_to('/login') unless signed_in?
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    
  end
  
  def create
    user = User.find_by(email: params[:session][:email])    
    if user && user.authenticate(params[:session][:password])
      sign_in(user)      
      redirect_to posts_path
    else      
      render :controller => 'sessions', :action => 'new'      
    end
  end
  
  def destroy
    sign_out
    redirect_to :login 
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Members Only</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
	<% flash.each do |message_type, message| %>
		<%= content_tag :p, message, :id => message_type%>
	<% end %>
	<% if !@post.nil? %>
		<% @post.errors.full_messages.each do |message| %>
			<%= content_tag :p, message %>
		<% end %>
	<% end %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% @posts.each do |p| %>  
	<div class="post">
	  <div class="poster">
	  	<p>
	  	<%= p.created_at.to_formatted_s(:short) %>
	  	</p>
	  	<p>
	  	<%= display_name(p.user) %>
	  	</p>
	  </div>
	  <div class="postcontent">
		  <div class="posttitle">
		  	<%= p.title %>
		  </div>
		  
		  <div class="postbody">
		  	<%= p.body %>
		  </div>
	  </div>
	</div>
<% end %>
<%= link_to 'Create New Post', new_post_path %>
<% if signed_in? %>
	<%= link_to 'signout', logout_path, method: :delete %>
<% end %>

app/views/posts/new.html.erb
<h1>Submit Post</h1>
<%= form_for(@post) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br> 
  <%= f.submit "Submit Post" %>
  
<% end%>